package com.planner.config;

import com.planner.model.MealType;
import com.planner.model.Recipe;
import com.planner.repository.RecipeRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class DataInitializer implements CommandLineRunner {

    private final RecipeRepository recipeRepository;

    public DataInitializer(RecipeRepository recipeRepository) {
        this.recipeRepository = recipeRepository;
    }

    @Override
    public void run(String... args) {
        if (recipeRepository.count() > 0) {
            return;
        }

        List<Recipe> recipes = List.of(
                Recipe.builder()
                        .title("Гречка с лесными грибами")
                        .dietType("REGULAR")
                        .mealType(MealType.BREAKFAST)
                        .calories(380)
                        .protein(14)
                        .price(220)
                        .cuisine("Русская")
                        .cookingTime(25)
                        .ingredients("гречка, шампиньоны, белые грибы, яйцо, зелень, сливочное масло")
                        .instructions("Отварите гречку, обжарьте грибы с луком, смешайте и подайте с яйцом-пашот.")
                        .description("Сытный завтрак в русском стиле с большим количеством клетчатки.")
                        .imageUrl("https://example.com/grechka.jpg")
                        .build(),
                Recipe.builder()
                        .title("Запечённый лосось с брокколи")
                        .dietType("KETO")
                        .mealType(MealType.DINNER)
                        .calories(520)
                        .protein(42)
                        .price(620)
                        .cuisine("Скандинавская")
                        .cookingTime(30)
                        .ingredients("филе лосося, брокколи, лимон, сливочное масло, чеснок")
                        .instructions("Приправьте рыбу, запекайте 15 минут, брокколи обжарьте на сливочном масле.")
                        .description("Лёгкий ужин с хорошим балансом омега-3 и клетчатки.")
                        .imageUrl("https://example.com/salmon.jpg")
                        .build(),
                Recipe.builder()
                        .title("Салат с киноа и нутом")
                        .dietType("VEGAN")
                        .mealType(MealType.LUNCH)
                        .calories(410)
                        .protein(18)
                        .price(280)
                        .cuisine("Средиземноморская")
                        .cookingTime(20)
                        .ingredients("киноа, нут, томаты черри, огурец, зелень, оливковое масло, лимон")
                        .instructions("Отварите киноа, смешайте с нутом и овощами, заправьте лимонным соком.")
                        .description("Яркий салат с растительным белком и свежими овощами.")
                        .imageUrl("https://example.com/quinoa.jpg")
                        .build(),
                Recipe.builder()
                        .title("Творожные сырники из духовки")
                        .dietType("REGULAR")
                        .mealType(MealType.BREAKFAST)
                        .calories(330)
                        .protein(20)
                        .price(180)
                        .cuisine("Русская")
                        .cookingTime(35)
                        .ingredients("творог, яйцо, рисовая мука, ваниль, мёд, ягоды")
                        .instructions("Смешайте ингредиенты, сформируйте сырники и запекайте 20 минут.")
                        .description("Полезная версия классических сырников без жарки на масле.")
                        .imageUrl("https://example.com/syrniki.jpg")
                        .build(),
                Recipe.builder()
                        .title("Окрошка на кефире с индейкой")
                        .dietType("REGULAR")
                        .mealType(MealType.LUNCH)
                        .calories(290)
                        .protein(25)
                        .price(150)
                        .cuisine("Русская")
                        .cookingTime(40)
                        .ingredients("кефир, индейка, картофель, огурец, редис, яйцо, зелень")
                        .instructions("Отварите индейку и картофель, нарежьте все ингредиенты и залейте кефиром.")
                        .description("Освежающий обед с высоким содержанием белка.")
                        .imageUrl("https://example.com/okroshka.jpg")
                        .build(),
                Recipe.builder()
                        .title("Тёплый салат из киноа и запечённых овощей")
                        .dietType("VEGAN")
                        .mealType(MealType.DINNER)
                        .calories(430)
                        .protein(16)
                        .price(240)
                        .cuisine("Авторская")
                        .cookingTime(35)
                        .ingredients("киноа, баклажан, кабачок, перец, кинза, тахини")
                        .instructions("Запеките овощи, сварите киноа и смешайте с соусом тахини.")
                        .description("Полноценный ужин без продуктов животного происхождения.")
                        .imageUrl("https://example.com/quinoa-salad.jpg")
                        .build(),
                Recipe.builder()
                        .title("Куриное филе с булгуром и шпинатом")
                        .dietType("REGULAR")
                        .mealType(MealType.DINNER)
                        .calories(480)
                        .protein(45)
                        .price(260)
                        .cuisine("Авторская")
                        .cookingTime(30)
                        .ingredients("куриная грудка, булгур, шпинат, чеснок, йогуртовый соус")
                        .instructions("Обжарьте грудку, булгур тушите с овощами, подавайте с соусом.")
                        .description("Сытное блюдо после тренировки или активного дня.")
                        .imageUrl("https://example.com/chicken.jpg")
                        .build(),
                Recipe.builder()
                        .title("Зелёный смузи для перекуса")
                        .dietType("VEGAN")
                        .mealType(MealType.SNACK)
                        .calories(190)
                        .protein(8)
                        .price(90)
                        .cuisine("Авторская")
                        .cookingTime(10)
                        .ingredients("шпинат, банан, яблоко, миндальное молоко, чиа")
                        .instructions("Взбейте все ингредиенты в блендере до кремовой текстуры.")
                        .description("Быстрый перекус с витаминами и клетчаткой.")
                        .imageUrl("https://example.com/smoothie.jpg")
                        .build(),
                Recipe.builder()
                        .title("Салат табуле с киноа")
                        .dietType("VEGAN")
                        .mealType(MealType.SNACK)
                        .calories(220)
                        .protein(7)
                        .price(130)
                        .cuisine("Ближневосточная")
                        .cookingTime(25)
                        .ingredients("киноа, петрушка, мята, томаты, огурец, лимон, оливковое масло")
                        .instructions("Смешайте все ингредиенты и охладите перед подачей.")
                        .description("Лёгкий перекус или гарнир с ярким вкусом свежей зелени.")
                        .imageUrl("https://example.com/tabbouleh.jpg")
                        .build(),
                Recipe.builder()
                        .title("Рагу из нута и тыквы")
                        .dietType("VEGAN")
                        .mealType(MealType.DINNER)
                        .calories(360)
                        .protein(14)
                        .price(210)
                        .cuisine("Марокканская")
                        .cookingTime(40)
                        .ingredients("тыква, нут, томаты, чеснок, кориандр, зира")
                        .instructions("Тушите все ингредиенты 25 минут до мягкости.")
                        .description("Согревающее блюдо с восточными специями.")
                        .imageUrl("https://example.com/tagine.jpg")
                        .build(),
                Recipe.builder()
                        .title("Ягодный чизкейк без выпечки")
                        .dietType("REGULAR")
                        .mealType(MealType.SNACK)
                        .calories(250)
                        .protein(12)
                        .price(200)
                        .cuisine("Авторская")
                        .cookingTime(20)
                        .ingredients("творог, греческий йогурт, ягоды, овсяное печенье, мёд")
                        .instructions("Сделайте основу из печенья, сверху выложите творожный крем и ягоды.")
                        .description("Десерт без сахара, который можно приготовить заранее.")
                        .imageUrl("https://example.com/cheesecake.jpg")
                        .build(),
                Recipe.builder()
                        .title("Борщ с фасолью и сметаной")
                        .dietType("REGULAR")
                        .mealType(MealType.LUNCH)
                        .calories(340)
                        .protein(22)
                        .price(190)
                        .cuisine("Украинская")
                        .cookingTime(90)
                        .ingredients("говядина, свёкла, капуста, фасоль, морковь, лук, сметана")
                        .instructions("Варите бульон, добавьте овощи и фасоль, подавайте со сметаной.")
                        .description("Классический борщ с мягким вкусом и большим количеством овощей.")
                        .imageUrl("https://example.com/borscht.jpg")
                        .build(),
                Recipe.builder()
                        .title("Шакшука с нутом")
                        .dietType("REGULAR")
                        .mealType(MealType.BREAKFAST)
                        .calories(360)
                        .protein(18)
                        .price(210)
                        .cuisine("Средиземноморская")
                        .cookingTime(25)
                        .ingredients("яйца, нут, томаты, перец, зира, паприка")
                        .instructions("Обжарьте овощи, добавьте нут и яйца, тушите до готовности.")
                        .description("Острый белковый завтрак в сковороде.")
                        .imageUrl("https://example.com/shakshuka.jpg")
                        .build(),
                Recipe.builder()
                        .title("Смузи-боул с манго и чиа")
                        .dietType("VEGAN")
                        .mealType(MealType.BREAKFAST)
                        .calories(310)
                        .protein(9)
                        .price(170)
                        .cuisine("Авторская")
                        .cookingTime(10)
                        .ingredients("манго, банан, кокосовое молоко, чиа, орехи")
                        .instructions("Взбейте в блендере и украсьте орехами и чиа.")
                        .description("Свежий завтрак с быстрыми углеводами и полезными жирами.")
                        .imageUrl("https://example.com/smoothie-bowl.jpg")
                        .build(),
                Recipe.builder()
                        .title("Белковый омлет с шпинатом")
                        .dietType("KETO")
                        .mealType(MealType.BREAKFAST)
                        .calories(280)
                        .protein(24)
                        .price(160)
                        .cuisine("Авторская")
                        .cookingTime(15)
                        .ingredients("яичные белки, шпинат, творожный сыр, масло гхи")
                        .instructions("Обжарьте шпинат, добавьте белки и сыр, доведите до готовности.")
                        .description("Лёгкий кето-завтрак с большим количеством белка.")
                        .imageUrl("https://example.com/protein-omelette.jpg")
                        .build(),
                Recipe.builder()
                        .title("Тыквенный крем-суп с чечевицей")
                        .dietType("VEGAN")
                        .mealType(MealType.LUNCH)
                        .calories(360)
                        .protein(16)
                        .price(180)
                        .cuisine("Европейская")
                        .cookingTime(35)
                        .ingredients("тыква, красная чечевица, кокосовое молоко, куркума, чеснок")
                        .instructions("Варите ингредиенты до мягкости, пробейте блендером.")
                        .description("Густой суп, который согреет в холодный день.")
                        .imageUrl("https://example.com/pumpkin-soup.jpg")
                        .build(),
                Recipe.builder()
                        .title("Суп мисо с лососем и шпинатом")
                        .dietType("KETO")
                        .mealType(MealType.LUNCH)
                        .calories(320)
                        .protein(28)
                        .price(340)
                        .cuisine("Японская")
                        .cookingTime(25)
                        .ingredients("лосось, мисо паста, шпинат, водоросли, тофу")
                        .instructions("Сварите бульон, добавьте мисо, рыбу и шпинат перед подачей.")
                        .description("Низкоуглеводный суп с ярким вкусом мисо.")
                        .imageUrl("https://example.com/miso-salmon.jpg")
                        .build(),
                Recipe.builder()
                        .title("Будда-боул с киноа и темпе")
                        .dietType("VEGAN")
                        .mealType(MealType.LUNCH)
                        .calories(430)
                        .protein(22)
                        .price(260)
                        .cuisine("Паназиатская")
                        .cookingTime(30)
                        .ingredients("киноа, темпе, авокадо, морковь, свекла, арахисовый соус")
                        .instructions("Разложите ингредиенты в боул и полейте соусом.")
                        .description("Цветной боул с балансом белков, жиров и углеводов.")
                        .imageUrl("https://example.com/buddha-bowl.jpg")
                        .build(),
                Recipe.builder()
                        .title("Салат с булгуром и фетой")
                        .dietType("REGULAR")
                        .mealType(MealType.LUNCH)
                        .calories(400)
                        .protein(15)
                        .price(210)
                        .cuisine("Греческая")
                        .cookingTime(25)
                        .ingredients("булгур, фета, оливки, огурцы, томаты, оливковое масло")
                        .instructions("Отварите булгур, смешайте с овощами и фетой.")
                        .description("Свежий салат в средиземноморском стиле.")
                        .imageUrl("https://example.com/bulgur-salad.jpg")
                        .build(),
                Recipe.builder()
                        .title("Фалафель из запечённого нута")
                        .dietType("VEGAN")
                        .mealType(MealType.LUNCH)
                        .calories(370)
                        .protein(17)
                        .price(190)
                        .cuisine("Ближневосточная")
                        .cookingTime(40)
                        .ingredients("нут, лук, кинза, чеснок, тахини, специи")
                        .instructions("Сформируйте шарики и запекайте до хруста.")
                        .description("Полезная альтернатива жареному фалафелю.")
                        .imageUrl("https://example.com/falafel.jpg")
                        .build(),
                Recipe.builder()
                        .title("Салат с тунцом и фасолью")
                        .dietType("KETO")
                        .mealType(MealType.LUNCH)
                        .calories(350)
                        .protein(30)
                        .price(250)
                        .cuisine("Итальянская")
                        .cookingTime(20)
                        .ingredients("тунец, фасоль каннеллини, рукола, оливковое масло, лимон")
                        .instructions("Смешайте ингредиенты и подавайте охлаждёнными.")
                        .description("Белковый салат для лёгкого обеда.")
                        .imageUrl("https://example.com/tuna-salad.jpg")
                        .build(),
                Recipe.builder()
                        .title("Лобио с орехами по-грузински")
                        .dietType("VEGAN")
                        .mealType(MealType.DINNER)
                        .calories(410)
                        .protein(19)
                        .price(200)
                        .cuisine("Грузинская")
                        .cookingTime(45)
                        .ingredients("красная фасоль, орехи, кинза, чеснок, хмели-сунели")
                        .instructions("Отварите фасоль и тушите с ореховой пастой и специями.")
                        .description("Плотное блюда без мяса с характерным ароматом.")
                        .imageUrl("https://example.com/lobio.jpg")
                        .build(),
                Recipe.builder()
                        .title("Треска на пару с зелёными овощами")
                        .dietType("REGULAR")
                        .mealType(MealType.DINNER)
                        .calories(370)
                        .protein(34)
                        .price(320)
                        .cuisine("Скандинавская")
                        .cookingTime(25)
                        .ingredients("филе трески, стручковая фасоль, горошек, лимон, масло")
                        .instructions("Готовьте рыбу на пару, овощи припустите и подавайте с лимоном.")
                        .description("Лёгкий ужин с высоким содержанием белка.")
                        .imageUrl("https://example.com/cod-steam.jpg")
                        .build(),
                Recipe.builder()
                        .title("Говядина томлёная с киноа")
                        .dietType("REGULAR")
                        .mealType(MealType.DINNER)
                        .calories(540)
                        .protein(42)
                        .price(380)
                        .cuisine("Авторская")
                        .cookingTime(70)
                        .ingredients("говядина, киноа, томаты, сельдерей, морковь")
                        .instructions("Тушите говядину до мягкости, подавайте с киноа и соусом.")
                        .description("Сытный вечерний вариант после активного дня.")
                        .imageUrl("https://example.com/beef-quinoa.jpg")
                        .build(),
                Recipe.builder()
                        .title("Тофу терияки с рисовой лапшой")
                        .dietType("VEGAN")
                        .mealType(MealType.DINNER)
                        .calories(420)
                        .protein(20)
                        .price(260)
                        .cuisine("Азиатская")
                        .cookingTime(30)
                        .ingredients("тофу, рисовая лапша, соус терияки, брокколи, кунжут")
                        .instructions("Обжарьте тофу в соусе и смешайте с лапшой и овощами.")
                        .description("Азиатская классика без продуктов животного происхождения.")
                        .imageUrl("https://example.com/tofu-teriyaki.jpg")
                        .build(),
                Recipe.builder()
                        .title("Чили с индейкой и фасолью")
                        .dietType("REGULAR")
                        .mealType(MealType.DINNER)
                        .calories(480)
                        .protein(38)
                        .price(240)
                        .cuisine("Мексиканская")
                        .cookingTime(50)
                        .ingredients("фарш индейки, фасоль, томаты, кукуруза, специи")
                        .instructions("Тушите всё вместе до насыщенного вкуса, подавайте с зеленью.")
                        .description("Пряное рагу для прохладного вечера.")
                        .imageUrl("https://example.com/turkey-chili.jpg")
                        .build(),
                Recipe.builder()
                        .title("Баклажаны по-азиатски с кунжутом")
                        .dietType("VEGAN")
                        .mealType(MealType.DINNER)
                        .calories(360)
                        .protein(11)
                        .price(190)
                        .cuisine("Азиатская")
                        .cookingTime(30)
                        .ingredients("баклажаны, соевый соус, мёд, чили, кунжут")
                        .instructions("Запеките баклажаны и глазируйте соусом.")
                        .description("Пикантное блюдо для любителей остроты.")
                        .imageUrl("https://example.com/eggplant.jpg")
                        .build(),
                Recipe.builder()
                        .title("Сэндвич с индейкой и песто")
                        .dietType("REGULAR")
                        .mealType(MealType.SNACK)
                        .calories(320)
                        .protein(20)
                        .price(150)
                        .cuisine("Европейская")
                        .cookingTime(15)
                        .ingredients("цельнозерновой хлеб, индейка, песто, сыр, салат")
                        .instructions("Соберите сэндвич и поджарьте на гриле.")
                        .description("Плотный перекус в дороге.")
                        .imageUrl("https://example.com/turkey-sandwich.jpg")
                        .build(),
                Recipe.builder()
                        .title("Роллы из огурца с крем-сыром и лососем")
                        .dietType("KETO")
                        .mealType(MealType.SNACK)
                        .calories(210)
                        .protein(16)
                        .price(180)
                        .cuisine("Авторская")
                        .cookingTime(10)
                        .ingredients("огурец, крем-сыр, лосось, укроп, лимон")
                        .instructions("Нарежьте огурец, сверните с начинкой и охладите.")
                        .description("Свежий кето-перекус за 10 минут.")
                        .imageUrl("https://example.com/cucumber-rolls.jpg")
                        .build(),
                Recipe.builder()
                        .title("Хумус с печёным перцем")
                        .dietType("VEGAN")
                        .mealType(MealType.SNACK)
                        .calories(240)
                        .protein(9)
                        .price(140)
                        .cuisine("Средиземноморская")
                        .cookingTime(20)
                        .ingredients("нут, тахини, печёный перец, лимон, тмин")
                        .instructions("Взбейте в блендере и подавайте с овощными палочками.")
                        .description("Полезный дип для перекуса или добавки к салату.")
                        .imageUrl("https://example.com/hummus.jpg")
                        .build()
        );

        recipes.forEach(recipeRepository::save);
    }
}
